[versions]
agp = "8.13.2"
kotlin = "2.2.21"
compose = "1.9.3"
# noinspection NewerVersionAvailable
dokka = "1.9.20"
maven-publish = "0.35.0"
kavaref-core = "1.0.2"
kavaref-extension = "1.0.2"
androidx-core-ktx = "1.17.0"
androidx-fragment-ktx = "1.8.9"
androidx-activity = "1.12.1"
androidx-appcompat = "1.7.1"
androidx-recyclerview = "1.4.0"
androidx-viewpager = "1.1.0"
androidx-viewpager2 = "1.1.0"
# noinspection GradleDependency
material = "1.11.0"
constraintlayout = "2.2.1"
androidx-test-ext-junit = "1.3.0"
androidx-test-espresso-core = "3.7.0"
junit = "4.13.2"
# noinspection GradleDependency
android-lint = "31.9.0"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }

[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kavaref-core = { group = "com.highcapable.kavaref", name = "kavaref-core", version.ref = "kavaref-core" }
kavaref-extension = { group = "com.highcapable.kavaref", name = "kavaref-extension", version.ref = "kavaref-extension" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment-ktx" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidx-activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recyclerview" }
androidx-viewpager = { group = "androidx.viewpager", name = "viewpager", version.ref = "androidx-viewpager" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "androidx-viewpager2" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso-core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
android-lint = { group = "com.android.tools.lint", name = "lint", version.ref = "android-lint" }
android-lint-api = { group = "com.android.tools.lint", name = "lint-api", version.ref = "android-lint" }
android-lint-checks = { group = "com.android.tools.lint", name = "lint-checks", version.ref = "android-lint" }
android-lint-tests = { group = "com.android.tools.lint", name = "lint-tests", version.ref = "android-lint" }